### PR TITLE
Add support for conversion to text

### PR DESCRIPTION
**Pull request by lucaspiller**
Add supports for conversion to plain text. The `txt` action supports the following files:

* Word documents
* OpenDocument Text documents
* PDF files (with `pdftotext` from Poppler)
* HTML files (with Nokogiri)
* images (this just calls the `ocr_text` task)

This also fixes a bug where OCR conversion may fail for more exotic file types (e.g. bitmaps).

### CODE REVIEW

**Comment by lucaspiller** [comment]
@vjt Ping

**Comment by vjt** [comment]
Looks good, thank you.

Questions:

* have you investigated using apache tika to extract the text? It supports off the shelf a variety of formats

* would it be better to `@tempfile.close` to ensure the on-disk file to not linger around until GC?

Thanks again,

~Marcello

**Comment by vjt** [comment]
PS. for readers, the CI build fails because of differences in OOO configuration across environments. As we target mainly our environment, and specs pass on it, we are postponing fixing the Travis build.

**Comment by lucaspiller** [comment]
As this PR stands, the only extra dependency a user needs is Poppler, and that's only if they want PDF to TXT conversion. I assume Tika+Java is going to be a bit tricky to setup, so I'd prefer to have Tika as an option, rather than the default - I'll investigate how complicated it is to get working.

On the other hand, [Tika integrates with Tesseract now](https://wiki.apache.org/tika/TikaOCR), so we could just have a single Heathen 'to text' converter that calls Tika.

**Comment by vjt** [comment]
Makes sense. I'd go with the current setup then as of now, and investigate full Tika support later.

**Pull request merged**
