### PR TITLE
Chore/update dependencies

### PR DESCRIPTION
**Pull request by tagliala**
Also:

- Alphabetize gems
- Enforce dependencies to prevent unwanted breaking changes
- Ignores default `/storage` directory

### CODE REVIEW

**Comment by vjt** [comment]
why pinning all the versions? Isn't that the job of Gemfile.lock? Wouldn't this make upgrades require more effort?

**Comment by tagliala** [comment]
This is a personal opinion. I've explained why I use this approach in the commit message here: b6612bfee390afa0ec770c5b80ef8960e8e692e9

Will elaborate more:

Given that a dependency follows SemVer, it should be safer to run `bundle update` by default

> Wouldn't this make upgrades require more effort?

Yes, it will require more attention to upgrade major version bumps and 0.x gems

PS: we can add @dependabot here to take care of dependencies, it also bumps up `Gemfile`

**Comment by vjt** [comment]
With the help of @dependabot then these changes make total sense.

Thanks

**Comment by tagliala** [comment]
@vjt if I merge this, could you please enable dependabot on this repo?

**Comment by vjt** [comment]
@tagliala you've got Admin rights now on this repo. Thank you

**Pull request merged**
